### PR TITLE
Create DOM-and-JavaScript.md

### LINKED ISSUE #2: DOM and JavaScript
Explain about Document Object Model and the role of JavaScript in it. Create Separate markdown file in the repository.

### PR DESCRIPTION
**Pull request by praveenscience**
Added the first page.

Fixes #2.

### CODE REVIEW

**Comment by praveenscience** [comment]
This is a start for the DOM & JavaScript article. I have written a lot of articles in my blog, something like this: [ES6 arrow functions and arguments](https://blog.praveen.science/es6-arrow-functions-and-arguments/). Hope this style of writing is alright?

**Comment by neilchauhan2** [comment]
@praveenscience Awesome work brother 👍. I would highly appreciate it, if you could provide a little more explanation with an example.

**Comment by praveenscience** [comment]
@neilchauhan2 Sure. Will do more then... Thanks for the motivation... 😃

**Comment by praveenscience** [comment]
@neilchauhan2 Can try finishing this today. Sorry mate, caught up with client visits and I am free today evening (BST)... Will do it by EoD. 😃

**Comment by neilchauhan2** [comment]
@praveenscience Perfect 👍

**Comment by praveenscience** [comment]
@neilchauhan2 Added... 👍

**Pull request merged**
